/* 
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InformationQuerysApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class InformationQuerysApiTests
    {
        private InformationQuerysApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InformationQuerysApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InformationQuerysApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' InformationQuerysApi
            //Assert.IsInstanceOfType(typeof(InformationQuerysApi), instance, "instance is a InformationQuerysApi");
        }

        
        /// <summary>
        /// Test AddInformationQuery
        /// </summary>
        [Test]
        public void AddInformationQueryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InformationQuery informationQuery = null;
            //var response = instance.AddInformationQuery(informationQuery);
            //Assert.IsInstanceOf<InformationQuery> (response, "response is InformationQuery");
        }
        
        /// <summary>
        /// Test DeleteInformationQuery
        /// </summary>
        [Test]
        public void DeleteInformationQueryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.DeleteInformationQuery(id);
            
        }
        
        /// <summary>
        /// Test FindInformationQuerys
        /// </summary>
        [Test]
        public void FindInformationQuerysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> tags = null;
            //int? limit = null;
            //var response = instance.FindInformationQuerys(tags, limit);
            //Assert.IsInstanceOf<List<InformationQuery>> (response, "response is List<InformationQuery>");
        }
        
        /// <summary>
        /// Test FindInformationqueryById
        /// </summary>
        [Test]
        public void FindInformationqueryByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.FindInformationqueryById(id);
            //Assert.IsInstanceOf<InformationQuery> (response, "response is InformationQuery");
        }
        
    }

}
