/* 
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SystemInformationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SystemInformationsApiTests
    {
        private SystemInformationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SystemInformationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SystemInformationsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SystemInformationsApi
            //Assert.IsInstanceOfType(typeof(SystemInformationsApi), instance, "instance is a SystemInformationsApi");
        }

        
        /// <summary>
        /// Test AddSystemInformation
        /// </summary>
        [Test]
        public void AddSystemInformationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SystemInformation systemInformation = null;
            //var response = instance.AddSystemInformation(systemInformation);
            //Assert.IsInstanceOf<SystemInformation> (response, "response is SystemInformation");
        }
        
        /// <summary>
        /// Test DeleteSystemInformation
        /// </summary>
        [Test]
        public void DeleteSystemInformationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.DeleteSystemInformation(id);
            
        }
        
        /// <summary>
        /// Test FindSystemInformations
        /// </summary>
        [Test]
        public void FindSystemInformationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> tags = null;
            //int? limit = null;
            //var response = instance.FindSystemInformations(tags, limit);
            //Assert.IsInstanceOf<List<SystemInformation>> (response, "response is List<SystemInformation>");
        }
        
        /// <summary>
        /// Test FindSysteminformationById
        /// </summary>
        [Test]
        public void FindSysteminformationByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.FindSysteminformationById(id);
            //Assert.IsInstanceOf<SystemInformation> (response, "response is SystemInformation");
        }
        
    }

}
