/* 
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.io.pharmatrace.api.scin.public.api;
using Org.OpenAPITools.io.pharmatrace.api.scin.public.model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing LegalTxTerms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LegalTxTermsTests
    {
        // TODO uncomment below to declare an instance variable for LegalTxTerms
        //private LegalTxTerms instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LegalTxTerms
            //instance = new LegalTxTerms();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LegalTxTerms
        /// </summary>
        [Test]
        public void LegalTxTermsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LegalTxTerms
            //Assert.IsInstanceOfType<LegalTxTerms> (instance, "variable 'instance' is a LegalTxTerms");
        }


        /// <summary>
        /// Test the property 'TimestampValidFrom'
        /// </summary>
        [Test]
        public void TimestampValidFromTest()
        {
            // TODO unit test for the property 'TimestampValidFrom'
        }
        /// <summary>
        /// Test the property 'TimestampValidUntil'
        /// </summary>
        [Test]
        public void TimestampValidUntilTest()
        {
            // TODO unit test for the property 'TimestampValidUntil'
        }
        /// <summary>
        /// Test the property 'ValidityTolerance'
        /// </summary>
        [Test]
        public void ValidityToleranceTest()
        {
            // TODO unit test for the property 'ValidityTolerance'
        }
        /// <summary>
        /// Test the property 'TermsId'
        /// </summary>
        [Test]
        public void TermsIdTest()
        {
            // TODO unit test for the property 'TermsId'
        }
        /// <summary>
        /// Test the property 'TermsVersion'
        /// </summary>
        [Test]
        public void TermsVersionTest()
        {
            // TODO unit test for the property 'TermsVersion'
        }
        /// <summary>
        /// Test the property 'TermsIdPreviousVersion'
        /// </summary>
        [Test]
        public void TermsIdPreviousVersionTest()
        {
            // TODO unit test for the property 'TermsIdPreviousVersion'
        }
        /// <summary>
        /// Test the property 'TermsText'
        /// </summary>
        [Test]
        public void TermsTextTest()
        {
            // TODO unit test for the property 'TermsText'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Legislation'
        /// </summary>
        [Test]
        public void LegislationTest()
        {
            // TODO unit test for the property 'Legislation'
        }

    }

}
