/* 
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.io.pharmatrace.api.scin.public.api;
using Org.OpenAPITools.io.pharmatrace.api.scin.public.model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ContainersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ContainersApiTests
    {
        private ContainersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ContainersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContainersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ContainersApi
            //Assert.IsInstanceOfType(typeof(ContainersApi), instance, "instance is a ContainersApi");
        }

        
        /// <summary>
        /// Test AddContainer
        /// </summary>
        [Test]
        public void AddContainerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Container container = null;
            //var response = instance.AddContainer(container);
            //Assert.IsInstanceOf<Container> (response, "response is Container");
        }
        
        /// <summary>
        /// Test DeleteContainer
        /// </summary>
        [Test]
        public void DeleteContainerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.DeleteContainer(id);
            
        }
        
        /// <summary>
        /// Test FindContainerById
        /// </summary>
        [Test]
        public void FindContainerByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.FindContainerById(id);
            //Assert.IsInstanceOf<Container> (response, "response is Container");
        }
        
        /// <summary>
        /// Test FindContainers
        /// </summary>
        [Test]
        public void FindContainersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> tags = null;
            //int? limit = null;
            //var response = instance.FindContainers(tags, limit);
            //Assert.IsInstanceOf<List<Container>> (response, "response is List<Container>");
        }
        
    }

}
