/* 
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.io.pharmatrace.api.scin.public.api;
using Org.OpenAPITools.io.pharmatrace.api.scin.public.model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InformationQueryResponsesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class InformationQueryResponsesApiTests
    {
        private InformationQueryResponsesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InformationQueryResponsesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InformationQueryResponsesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' InformationQueryResponsesApi
            //Assert.IsInstanceOfType(typeof(InformationQueryResponsesApi), instance, "instance is a InformationQueryResponsesApi");
        }

        
        /// <summary>
        /// Test AddInformationQueryResponse
        /// </summary>
        [Test]
        public void AddInformationQueryResponseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InformationQueryResponse informationQueryResponse = null;
            //var response = instance.AddInformationQueryResponse(informationQueryResponse);
            //Assert.IsInstanceOf<InformationQueryResponse> (response, "response is InformationQueryResponse");
        }
        
        /// <summary>
        /// Test DeleteInformationQueryResponse
        /// </summary>
        [Test]
        public void DeleteInformationQueryResponseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.DeleteInformationQueryResponse(id);
            
        }
        
        /// <summary>
        /// Test FindInformationQueryResponses
        /// </summary>
        [Test]
        public void FindInformationQueryResponsesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> tags = null;
            //int? limit = null;
            //var response = instance.FindInformationQueryResponses(tags, limit);
            //Assert.IsInstanceOf<List<InformationQueryResponse>> (response, "response is List<InformationQueryResponse>");
        }
        
        /// <summary>
        /// Test FindInformationqueryresponseById
        /// </summary>
        [Test]
        public void FindInformationqueryresponseByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.FindInformationqueryresponseById(id);
            //Assert.IsInstanceOf<InformationQueryResponse> (response, "response is InformationQueryResponse");
        }
        
    }

}
