/* 
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.io.pharmatrace.api.scin.public.api;
using Org.OpenAPITools.io.pharmatrace.api.scin.public.model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StakeholdersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StakeholdersApiTests
    {
        private StakeholdersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StakeholdersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StakeholdersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StakeholdersApi
            //Assert.IsInstanceOfType(typeof(StakeholdersApi), instance, "instance is a StakeholdersApi");
        }

        
        /// <summary>
        /// Test AddStakeholder
        /// </summary>
        [Test]
        public void AddStakeholderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Stakeholder stakeholder = null;
            //var response = instance.AddStakeholder(stakeholder);
            //Assert.IsInstanceOf<Stakeholder> (response, "response is Stakeholder");
        }
        
        /// <summary>
        /// Test DeleteStakeholder
        /// </summary>
        [Test]
        public void DeleteStakeholderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.DeleteStakeholder(id);
            
        }
        
        /// <summary>
        /// Test FindStakeholderById
        /// </summary>
        [Test]
        public void FindStakeholderByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.FindStakeholderById(id);
            //Assert.IsInstanceOf<Stakeholder> (response, "response is Stakeholder");
        }
        
        /// <summary>
        /// Test FindStakeholders
        /// </summary>
        [Test]
        public void FindStakeholdersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> tags = null;
            //int? limit = null;
            //var response = instance.FindStakeholders(tags, limit);
            //Assert.IsInstanceOf<List<Stakeholder>> (response, "response is List<Stakeholder>");
        }
        
    }

}
