/* 
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Container
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContainerTests
    {
        // TODO uncomment below to declare an instance variable for Container
        //private Container instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Container
            //instance = new Container();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Container
        /// </summary>
        [Test]
        public void ContainerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Container
            //Assert.IsInstanceOfType<Container> (instance, "variable 'instance' is a Container");
        }


        /// <summary>
        /// Test the property 'ContainerId'
        /// </summary>
        [Test]
        public void ContainerIdTest()
        {
            // TODO unit test for the property 'ContainerId'
        }
        /// <summary>
        /// Test the property 'EpcCode'
        /// </summary>
        [Test]
        public void EpcCodeTest()
        {
            // TODO unit test for the property 'EpcCode'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Barcode'
        /// </summary>
        [Test]
        public void BarcodeTest()
        {
            // TODO unit test for the property 'Barcode'
        }
        /// <summary>
        /// Test the property 'RfId'
        /// </summary>
        [Test]
        public void RfIdTest()
        {
            // TODO unit test for the property 'RfId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'CurrentLocationId'
        /// </summary>
        [Test]
        public void CurrentLocationIdTest()
        {
            // TODO unit test for the property 'CurrentLocationId'
        }
        /// <summary>
        /// Test the property 'OwnerStakeholderId'
        /// </summary>
        [Test]
        public void OwnerStakeholderIdTest()
        {
            // TODO unit test for the property 'OwnerStakeholderId'
        }
        /// <summary>
        /// Test the property 'ParentContainerId'
        /// </summary>
        [Test]
        public void ParentContainerIdTest()
        {
            // TODO unit test for the property 'ParentContainerId'
        }

    }

}
